### ISSUE TITLE
Mute and solo on linked channels not working properly

### ISSUE THREAD

**Issue by rikuturunen** [MatthewInch/UI24RBridge#5]
Latest release (065) fixed the missing stereo link for volume faders, good job!

Will you add same functionality to solo and mute buttons (when you mute member of linked channels, the other one toggles too)? Thanks and keep up the good work!

**Comment by MatthewInch** [comment]
In the 0.6.6 version the mute/solo button is fixed.

**Comment by MatthewInch** [comment]
In the next release (v0.6.7) the solo/mute will be linked :D

**Comment by rikuturunen** [comment]
Still not working for me (linked solo and mute). Only one channel gets
muted or soloed.

to 23. tammik. 2020 klo 2.07 MatthewInch (notifications@github.com)
kirjoitti:

**Comment by MatthewInch** [comment]
The modification is in the source code but (because it was too late 🙂) I didn't create the v0.6.7 release package. I will create it today evening.

**Comment by rikuturunen** [comment]
Ah. Ok! Great work so far again :)

to 23. tammik. 2020 klo 10.54 MatthewInch (notifications@github.com)
kirjoitti:

**Comment by MatthewInch** [comment]
I upload the new release (there is a new function: mtk rec start/stop wiht rec button)

**Comment by rikuturunen** [comment]
Works perfectly! Thanks :)

to 23. tammik. 2020 klo 23.43 MatthewInch (notifications@github.com)
kirjoitti:
